
kind: Namespace
apiVersion: v1
metadata:
  name: strinity
  labels:
    name: strinity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strinity-deployment
  namespace: strinity
  labels:
    app: strinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strinity
  template:
    metadata:
      labels:
        app: strinity
    spec:
      nodeSelector:
        purpose: general
      containers:
      - name: strinity
        image: charlie83gs/react_page:latest
        ports:
        - containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: strinity-service
  namespace: strinity
spec:
  selector:
    app: strinity
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: strinity
  namespace: strinity
spec:
  hosts:
  - "*"
  gateways:
  - istio-custom/devops-gateway
  http:
    - name: "strinity-routes"
      match:
      - uri: 
          prefix: "/strinity"
      route:
        - destination:
            host: strinity-service.cgomez.svc.cluster.local

